[tox]
envlist =
    py27-django111
    py36-django{111,2,3}
    py37-django{111,2,3}
    py38-django{111,2,3}
    py39-django{111,2,3,4}
    py311-django{3,4}
    py313-django{5,6}
    py314-django{5,6}
    flake8


[testenv]
deps =
    django111: Django==1.11
    django2: Django==2.*
    django3: Django==3.*
    django4: Django==4.*
    django5: Django==5.*
    django6: Django==6.*

    django111: pytest-django<4
    django2: pytest-django<4
    django3: pytest-django>=4,<5
    django4: pytest-django>=4,<5
    django5: pytest-django>=4,<5
    django6: pytest-django>=4,<5

    pytest
    psycopg2-binary

commands =
    pip install -e .
    py.test {posargs}
